default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: postgres
  port: 5432
  pool: 5

development:
  <<: *default
  database: Nanoservice_development

test:
  <<: *default
  database: Nanoservice_test

production:
  <<: *default
  database: Nanoservice_production
